### ISSUE TITLE
App crash on installation

### ISSUE THREAD

**Issue by mats93** [isberg1/Android-project#4]
**Describe the bug**
The app crashes first time it's installed.

**To Reproduce**
1. Uninstall the app.
2. Run the code in the emulator
3. See crash.

**Expected behavior**
App should not crash.

**Screenshots or code**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.AndroidDriverImt3673.prosjekt, PID: 22473
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraDevice.close()' on a null object reference
        at com.AndroidDriverImt3673.prosjekt.CameraClass$2.onError(CameraClass.java:157)
        at android.hardware.camera2.impl.CameraDeviceImpl$8.run(CameraDeviceImpl.java:348)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by mats93** [comment]
Fixed in 208626ef7a33250368db345523bac8fab20867dc
