### ISSUE TITLE
App crash because of missing permission

### ISSUE THREAD

**Issue by mats93** [isberg1/Android-project#5]
**Describe the bug**
The app crashes after first time installation when clicking on "Start" and then "Stop" because the required permissions are not set.

**To Reproduce**
1. Uninstall the app
2. Run the code on the emulator
3. Press "allow" on all permissions that pop up
4. Press "Start"
5. Press "Stop"
6. See error

**Expected behavior**
The permission should be set first time the app starts.    
The missing permission is "Allow to accesss the devic's location".     
This is aksed for the second time the app starts, the bug is then "removed".

**Screenshots or code**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.AndroidDriverImt3673.prosjekt, PID: 23578
    java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
        at android.os.Parcel.createException(Parcel.java:1942)
        at android.os.Parcel.readException(Parcel.java:1910)
        at android.os.Parcel.readException(Parcel.java:1860)
        at android.location.ILocationManager$Stub$Proxy.getLastLocation(ILocationManager.java:866)
        at android.location.LocationManager.getLastKnownLocation(LocationManager.java:1420)
        at com.AndroidDriverImt3673.prosjekt.MainActivity.endTrip(MainActivity.java:344)
        at com.AndroidDriverImt3673.prosjekt.MainActivity$2.onClick(MainActivity.java:333)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.LocationManagerService.checkResolutionLevelIsSufficientForProviderUse(LocationManagerService.java:1492)
        at com.android.server.LocationManagerService.getLastLocation(LocationManagerService.java:2219)
        at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:159)
        at android.os.Binder.execTransact(Binder.java:731)
```

**Comment by mats93** [comment]
Fixed by @isberg1

**Comment by iammujtaba44** [comment]
@mats93 hey can you please share the solution cause i am facing the same problem
